### PR TITLE
Fix a few problems with driver downloading and antivirus

### PR DESCRIPTION
**Pull request by Bluebotlabz**
This fork fixes driver downloading by replacing aria2c with Windows's built-in curl command
It also replaces the dsfo executable with one from a verified source as the one included with the repo was triggering several antivirus applications: [VirusTotal](https://www.virustotal.com/gui/file/aaaa5e57a1ebbc912f7af4551bf9c49821f9ee2de3079e3a9f5f0d1bb4d8d478)

The new dsfo.exe was downloaded from [mysystemadmintips](https://www.mysysadmintips.com/-downloads-/Windows/Servers/dsfok.zip) and works with the scripts and also doesn't trigger antivirus detection

### CODE REVIEW

**Comment by RedGreenBlue09** [comment]
Thank you for your attention.
The installer is focused on compatibility, from Windows 8.1 and up. Curl is only available on Windows 10 1803+ as far as I know.
About dsfo, I the original is compressed using some software, I decompressed it for fun :). If it is causing too much false positive issues then I will bring back the original.

**Comment by Bluebotlabz** [comment]
Ok, I'm going to adjust the curl to use an installation local to the tool as the alternative doesn't work on windows 11 or 10 or maybe at all?

**Comment by Bluebotlabz** [comment]
I've just pushed a commit to the fork which changes the curl installation from the Windows installation to a curl binary included with the utility

**Comment by Bluebotlabz** [comment]
that's odd, I guess my PC just doesn't like Windows Phone utilities
it ways it couldn't find 930.txt or whatever when I tried it, which seemed to be because aria2c wasn't downloading it

**Comment by RedGreenBlue09** [comment]
> that's odd, I guess my PC just doesn't like Windows Phone utilities (it complains about WPInternals too) it ways it couldn't find 930.txt or whatever when I tried it, which seemed to be because aria2c wasn't downloading it

You nay try to get some logs and post it here for me. Remove >nul to get the output from the aria2c command.

**Comment by RedGreenBlue09** [comment]
> > that's odd, I guess my PC just doesn't like Windows Phone utilities (it complains about WPInternals too) it ways it couldn't find 930.txt or whatever when I tried it, which seemed to be because aria2c wasn't downloading it
> 
> You nay try to get some logs and post it here for me. Remove >nul to get the output from the aria2c command.

Oops, there is no >nul, try removing -q flag instead.

**Comment by Bluebotlabz** [comment]
Sure, I'll do it when I can use the PC again, also, do you mind if I use some of your script's code for my own installation script?

**Comment by RedGreenBlue09** [comment]
> Sure, I'll do it when I can use the PC again, also, do you mind if I use some of your script's code for my own installation script?

Yes. Also, remember to credit me ;)

**Comment by Bluebotlabz** [comment]
Thanks!
I'm trying to make a script like this, except it deploys WOA 64-bit to a micro SD card

Unfortunately, WOA's guide on how to do it is a little confusing...

**Pull request closed without merging**
